Repository BalloonBox-Inc/near-oracle-algorithm, pull requests merged in 2022-07, with the labels that each got.

#34 Feature/near 16
  .gitignore
  README.md
  config/config.json
  config/helper.py
  documentation/timeline.md
  main.py
  market/coinmarketcap.py
  support/feedback.py
  support/helper.py
  support/metrics_coinbase.py
  support/metrics_covalent.py
  support/metrics_plaid.py
  support/models.py
  support/score.py
  validator/covalent.py
Labels: covalent

#35 Feature/near 17
  README.md
  config/config.json
  images/logic_covalent.png
  main.py
  support/metrics_covalent.py
Labels: documentation

#38 #37 3 new fns for KYC template
  support/metrics_coinbase.py
  support/metrics_covalent.py
  support/metrics_plaid.py
Labels: enhancement

#39 Covalent API doc
  documentation/README.md
Labels: covalent

#40 feature/NEAR-36 -> dev
  .github/workflows/python-app.yml
  .gitignore
  config/helper.py
  main.py
  requirements.txt
  routers/__init__.py
  routers/coinbase.py
  routers/covalent.py
  routers/kyc.py
  routers/plaid.py
  schemas.py
Labels: enhancement

#43 #37 add /credit_score/kyc endpoint
  routers/kyc.py
  schemas.py
  support/metrics_coinbase.py
  support/metrics_covalent.py
  support/metrics_plaid.py
  validator/coinbase.py
Labels: enhancement

#44 Feature/near 17
  config/config.json
  demo1.0.py
  demo2.0.py
  market/coinmarketcap.py
  support/feedback.py
  support/helper.py
  support/metrics_covalent.py
  support/models.py
  support/score.py
  validator/covalent.py
Labels: covalent

#45 #15 set up unittest skeleton
  testing/tests/test_coinbase.py
  testing/tests/test_covalent.py
  testing/tests/test_plaid.py
Labels: covalent

#46 Feature/near 15
  demo2.0.py
  support/helper.py
  support/models.py
  testing/data/test_covalent.json
  unit_tests.py
Labels: covalent

#53 #49 params refactor, docstrings Plaid&Cbase
  .github/workflows/python-app.yml
  support/metrics_coinbase.py
  support/metrics_covalent.py
  support/metrics_plaid.py
  support/models.py
  testing/tests/test_coinbase.py
  testing/tests/test_covalent.py
  testing/tests/test_plaid.py
Labels: enhancement

#55 Complete Covalent Oracle
  .gitignore
  README.md
  config/config.json
  config/helper.py
  demo1.0.py
  demo2.0.py
  documentation/README.md
  documentation/timeline.md
  images/logic_covalent.png
  main.py
  market/coinmarketcap.py
  requirements.txt
  routers/__init__.py
  routers/coinbase.py
  routers/covalent.py
  routers/kyc.py
  routers/plaid.py
  schemas.py
  support/feedback.json
  support/feedback.py
  support/helper.py
  support/metrics_coinbase.py
  support/metrics_covalent.py
  support/metrics_plaid.py
  support/models.py
  support/score.py
  testing/data/test_covalent.json
  testing/tests/test_coinbase.py
  testing/tests/test_covalent.py
  testing/tests/test_plaid.py
  unit_tests.py
  validator/coinbase.py
  validator/covalent.py
Labels: enhancement

#61 set autopep8 formatter
  .gitignore
  .vscode/settings.json
  support/metrics_coinbase.py
  support/metrics_covalent.py
  support/metrics_plaid.py
Labels: enhancement

#64 Near 22
  .gitignore
  .vscode/settings.json
  config/config.json
  demo2.0.py
  pytest.ini
  requirements.txt
  routers/coinbase.py
  routers/covalent.py
  routers/kyc.py
  routers/plaid.py
  routers/schemas.py
  support/assessment.py
  support/database.py
  support/helper.py
  support/metrics_coinbase.py
  support/metrics_plaid.py
  support/score.py
  testing/data/README.md
  testing/tests/README.md
  tests/README.md
  tests/__init__.py
  tests/test_coinbase.json
  tests/test_coinbase.py
  tests/test_covalent.json
  tests/test_covalent.py
  tests/test_plaid.json
  tests/test_plaid.py
  unit_tests.py
Labels: enhancement, plaid
